#!/usr/bin/env bash
# Re-renders every Ingress the auth chart produces for dev-aws-1/auth,
# dev-aws-1/auth-dev and prod-aws-1/auth (read-only on both repos) into
# test/policy/testdata/chart-ingresses.yaml, which test/policy checks against the
# admission policies so a Helm upgrade is never rejected.
set -euo pipefail
here=$(cd "$(dirname "$0")/.." && pwd)
chart=${CHART:-$here/../charts/charts/auth}
infra=${INFRA:-$HOME/.ghq/gitlab.example.com/infra/k8s}
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT
cp -R "$chart" "$work/auth"
helm dependency build "$work/auth" >/dev/null
out=$here/test/policy/testdata/chart-ingresses.yaml
echo "# Generated by hack/render-chart-ingresses.sh — do not edit." > "$out"
for env in dev-aws-1/auth dev-aws-1/auth-dev prod-aws-1/auth; do
  helm template auth "$work/auth" -n auth -f "$infra/$env/values.yaml" |
    python3 -c '
import sys, yaml
env = sys.argv[1]
for d in yaml.safe_load_all(sys.stdin):
    if d and d.get("kind") == "Ingress":
        d["metadata"]["namespace"] = "auth"
        d["metadata"].setdefault("labels", {})["test.source"] = env.replace("/", "_")
        print("---"); print(yaml.safe_dump(d, sort_keys=True), end="")
' "$env" >> "$out"
done
echo "wrote $out"
